//swiftlint:disable file_length
//
//  WeatherAPI.swift
//  Baluchon
//
//  Created by Fabrice Etiennette on 25/12/2019.
//  Copyright © 2019 Fabrice Etiennette. All rights reserved.
//

import Foundation
import Moya

enum WeatherAPI {
    static private let weatherKey = valueForAPIKey(named: "darkSkyApiKey")

    case weather(Weather)
}

extension WeatherAPI: TargetType {
    var baseURL: URL {
        return URL(safeString: "https://api.darksky.net")
    }

    var path: String {
        switch self {
        case .weather(let weather):
            return "/forecast/\(WeatherAPI.weatherKey)/\(weather.latitude),\(weather.longitude)"
        }
    }

    var method: Moya.Method {
        switch self {
        case .weather:
            return .get
        }
    }

    var task: Task {
        switch self {
        case .weather(let weather):
            let bodyParameters = ["lang": weather.lang, "units": weather.units]
            return .requestParameters(parameters: bodyParameters, encoding: URLEncoding.default)
        }
    }

    var headers: [String: String]? {
        return [:]
    }

    var validationType: ValidationType {
        return .successCodes
    }

    var authorizationType: AuthorizationType {
        return .none
    }

    var sampleData: Data {
        var encodable: String!
        switch self {
        case .weather:
            encodable = """
            {
                "latitude": 37.8267,
                "longitude": -122.4233,
                "timezone": "America/Los_Angeles",
                "currently": {
                    "time": 1580110758,
                    "summary": "Ciel Dégagé",
                    "icon": "clear-night",
                    "nearestStormDistance": 6,
                    "nearestStormBearing": 322,
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 10.78,
                    "apparentTemperature": 10.78,
                    "dewPoint": 7.37,
                    "humidity": 0.79,
                    "pressure": 1026.8,
                    "windSpeed": 2.34,
                    "windGust": 2.86,
                    "windBearing": 278,
                    "cloudCover": 0.07,
                    "uvIndex": 0,
                    "visibility": 16.093,
                    "ozone": 318.1
                },
                "minutely": {
                    "summary": "Ciel dégagé pendant la prochaine heure.",
                    "icon": "clear-night",
                    "data": [
                        {
                            "time": 1580110740,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580110800,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580110860,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580110920,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580110980,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111040,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111100,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111160,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111220,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111280,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111340,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111400,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111460,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111520,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111580,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111640,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111700,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111760,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111820,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111880,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580111940,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112000,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112060,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112120,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112180,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112240,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112300,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112360,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112420,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112480,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112540,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112600,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112660,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112720,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112780,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112840,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112900,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580112960,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113020,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113080,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113140,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113200,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113260,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113320,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113380,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113440,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113500,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113560,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113620,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113680,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113740,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113800,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113860,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113920,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580113980,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114040,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114100,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114160,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114220,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114280,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        },
                        {
                            "time": 1580114340,
                            "precipIntensity": 0,
                            "precipProbability": 0
                        }
                    ]
                },
                "hourly": {
                    "summary": "Faibles passages nuageux toute la journée.",
                    "icon": "partly-cloudy-day",
                    "data": [
                        {
                            "time": 1580108400,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0418,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.99,
                            "apparentTemperature": 10.99,
                            "dewPoint": 7.45,
                            "humidity": 0.79,
                            "pressure": 1027,
                            "windSpeed": 2.58,
                            "windGust": 3.82,
                            "windBearing": 302,
                            "cloudCover": 0.09,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 318.5
                        },
                        {
                            "time": 1580112000,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0067,
                            "precipProbability": 0.04,
                            "precipType": "rain",
                            "temperature": 10.73,
                            "apparentTemperature": 10.73,
                            "dewPoint": 7.4,
                            "humidity": 0.8,
                            "pressure": 1026.8,
                            "windSpeed": 2.28,
                            "windGust": 2.59,
                            "windBearing": 265,
                            "cloudCover": 0.06,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.9
                        },
                        {
                            "time": 1580115600,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0118,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 11.06,
                            "apparentTemperature": 11.06,
                            "dewPoint": 7.87,
                            "humidity": 0.81,
                            "pressure": 1026.9,
                            "windSpeed": 2.45,
                            "windGust": 3.43,
                            "windBearing": 285,
                            "cloudCover": 0.04,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.5
                        },
                        {
                            "time": 1580119200,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 11.18,
                            "apparentTemperature": 11.18,
                            "dewPoint": 8.3,
                            "humidity": 0.82,
                            "pressure": 1027.4,
                            "windSpeed": 2.46,
                            "windGust": 3.88,
                            "windBearing": 302,
                            "cloudCover": 0.05,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.5
                        },
                        {
                            "time": 1580122800,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 10.88,
                            "apparentTemperature": 10.88,
                            "dewPoint": 8.47,
                            "humidity": 0.85,
                            "pressure": 1027.7,
                            "windSpeed": 2.19,
                            "windGust": 3.99,
                            "windBearing": 287,
                            "cloudCover": 0.07,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.6
                        },
                        {
                            "time": 1580126400,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0174,
                            "precipProbability": 0.05,
                            "precipType": "rain",
                            "temperature": 10.51,
                            "apparentTemperature": 10.51,
                            "dewPoint": 8.51,
                            "humidity": 0.87,
                            "pressure": 1027.8,
                            "windSpeed": 1.94,
                            "windGust": 3.7,
                            "windBearing": 289,
                            "cloudCover": 0.1,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.9
                        },
                        {
                            "time": 1580130000,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0408,
                            "precipProbability": 0.07,
                            "precipType": "rain",
                            "temperature": 10.13,
                            "apparentTemperature": 10.13,
                            "dewPoint": 8.49,
                            "humidity": 0.9,
                            "pressure": 1027.8,
                            "windSpeed": 1.86,
                            "windGust": 3.57,
                            "windBearing": 297,
                            "cloudCover": 0.14,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 318.7
                        },
                        {
                            "time": 1580133600,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0459,
                            "precipProbability": 0.08,
                            "precipType": "rain",
                            "temperature": 9.76,
                            "apparentTemperature": 9,
                            "dewPoint": 8.47,
                            "humidity": 0.92,
                            "pressure": 1028,
                            "windSpeed": 1.9,
                            "windGust": 3.54,
                            "windBearing": 264,
                            "cloudCover": 0.18,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 319.8
                        },
                        {
                            "time": 1580137200,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-night",
                            "precipIntensity": 0.0478,
                            "precipProbability": 0.07,
                            "precipType": "rain",
                            "temperature": 9.7,
                            "apparentTemperature": 8.92,
                            "dewPoint": 8.62,
                            "humidity": 0.93,
                            "pressure": 1028.4,
                            "windSpeed": 1.92,
                            "windGust": 3.42,
                            "windBearing": 265,
                            "cloudCover": 0.24,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 319.8
                        },
                        {
                            "time": 1580140800,
                            "summary": "Ciel Dégagé",
                            "icon": "clear-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 10.03,
                            "apparentTemperature": 10.03,
                            "dewPoint": 9.02,
                            "humidity": 0.93,
                            "pressure": 1029,
                            "windSpeed": 1.73,
                            "windGust": 3.34,
                            "windBearing": 264,
                            "cloudCover": 0.3,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 317.9
                        },
                        {
                            "time": 1580144400,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 10.75,
                            "apparentTemperature": 10.75,
                            "dewPoint": 9.76,
                            "humidity": 0.94,
                            "pressure": 1029.8,
                            "windSpeed": 1.68,
                            "windGust": 3.59,
                            "windBearing": 245,
                            "cloudCover": 0.36,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 315.1
                        },
                        {
                            "time": 1580148000,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0.0052,
                            "precipProbability": 0.04,
                            "precipType": "rain",
                            "temperature": 11.32,
                            "apparentTemperature": 11.32,
                            "dewPoint": 10.13,
                            "humidity": 0.92,
                            "pressure": 1030.1,
                            "windSpeed": 1.78,
                            "windGust": 3.69,
                            "windBearing": 263,
                            "cloudCover": 0.37,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 313.1
                        },
                        {
                            "time": 1580151600,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 12.06,
                            "apparentTemperature": 12.06,
                            "dewPoint": 10.26,
                            "humidity": 0.89,
                            "pressure": 1029.9,
                            "windSpeed": 2.09,
                            "windGust": 3.97,
                            "windBearing": 286,
                            "cloudCover": 0.35,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 312.9
                        },
                        {
                            "time": 1580155200,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 12.61,
                            "apparentTemperature": 12.61,
                            "dewPoint": 10.47,
                            "humidity": 0.87,
                            "pressure": 1029.6,
                            "windSpeed": 2.59,
                            "windGust": 4.42,
                            "windBearing": 238,
                            "cloudCover": 0.34,
                            "uvIndex": 3,
                            "visibility": 16.093,
                            "ozone": 313.6
                        },
                        {
                            "time": 1580158800,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0.0054,
                            "precipProbability": 0.05,
                            "precipType": "rain",
                            "temperature": 13.13,
                            "apparentTemperature": 13.13,
                            "dewPoint": 10.29,
                            "humidity": 0.83,
                            "pressure": 1029,
                            "windSpeed": 2.55,
                            "windGust": 3.37,
                            "windBearing": 257,
                            "cloudCover": 0.38,
                            "uvIndex": 3,
                            "visibility": 16.093,
                            "ozone": 314.2
                        },
                        {
                            "time": 1580162400,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 13.43,
                            "apparentTemperature": 13.43,
                            "dewPoint": 10.17,
                            "humidity": 0.81,
                            "pressure": 1028.7,
                            "windSpeed": 2.73,
                            "windGust": 3.41,
                            "windBearing": 259,
                            "cloudCover": 0.38,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 314.3
                        },
                        {
                            "time": 1580166000,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 13.49,
                            "apparentTemperature": 13.49,
                            "dewPoint": 9.96,
                            "humidity": 0.79,
                            "pressure": 1028.4,
                            "windSpeed": 2.8,
                            "windGust": 3.31,
                            "windBearing": 265,
                            "cloudCover": 0.38,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 314.1
                        },
                        {
                            "time": 1580169600,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 13.19,
                            "apparentTemperature": 13.19,
                            "dewPoint": 9.84,
                            "humidity": 0.8,
                            "pressure": 1028.4,
                            "windSpeed": 2.81,
                            "windGust": 3.17,
                            "windBearing": 257,
                            "cloudCover": 0.41,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 314.1
                        },
                        {
                            "time": 1580173200,
                            "summary": "Faibles Passages Nuageux",
                            "icon": "partly-cloudy-day",
                            "precipIntensity": 0.0069,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 12.47,
                            "apparentTemperature": 12.47,
                            "dewPoint": 9.53,
                            "humidity": 0.82,
                            "pressure": 1028.5,
                            "windSpeed": 2.75,
                            "windGust": 3.03,
                            "windBearing": 223,
                            "cloudCover": 0.5,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 314.3
                        },
                        {
                            "time": 1580176800,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0178,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 11.55,
                            "apparentTemperature": 11.55,
                            "dewPoint": 9.5,
                            "humidity": 0.87,
                            "pressure": 1028.4,
                            "windSpeed": 2.63,
                            "windGust": 2.87,
                            "windBearing": 286,
                            "cloudCover": 0.63,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 314.6
                        },
                        {
                            "time": 1580180400,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0297,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.97,
                            "apparentTemperature": 10.97,
                            "dewPoint": 9.22,
                            "humidity": 0.89,
                            "pressure": 1028.5,
                            "windSpeed": 2.49,
                            "windGust": 2.79,
                            "windBearing": 264,
                            "cloudCover": 0.73,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 314.3
                        },
                        {
                            "time": 1580184000,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0337,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.74,
                            "apparentTemperature": 10.74,
                            "dewPoint": 9.1,
                            "humidity": 0.9,
                            "pressure": 1028.8,
                            "windSpeed": 2.35,
                            "windGust": 2.88,
                            "windBearing": 283,
                            "cloudCover": 0.81,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 313.2
                        },
                        {
                            "time": 1580187600,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0339,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.67,
                            "apparentTemperature": 10.67,
                            "dewPoint": 8.96,
                            "humidity": 0.89,
                            "pressure": 1029.3,
                            "windSpeed": 2.2,
                            "windGust": 3.08,
                            "windBearing": 228,
                            "cloudCover": 0.87,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 311.5
                        },
                        {
                            "time": 1580191200,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0338,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.62,
                            "apparentTemperature": 10.62,
                            "dewPoint": 8.86,
                            "humidity": 0.89,
                            "pressure": 1029.5,
                            "windSpeed": 2.09,
                            "windGust": 3.19,
                            "windBearing": 252,
                            "cloudCover": 0.91,
                            "uvIndex": 0,
                            "visibility": 15.035,
                            "ozone": 310
                        },
                        {
                            "time": 1580194800,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0333,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.47,
                            "apparentTemperature": 10.47,
                            "dewPoint": 8.78,
                            "humidity": 0.89,
                            "pressure": 1029.5,
                            "windSpeed": 2.03,
                            "windGust": 3.09,
                            "windBearing": 262,
                            "cloudCover": 0.91,
                            "uvIndex": 0,
                            "visibility": 14.318,
                            "ozone": 308.7
                        },
                        {
                            "time": 1580198400,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.033,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.42,
                            "apparentTemperature": 10.42,
                            "dewPoint": 8.71,
                            "humidity": 0.89,
                            "pressure": 1029.3,
                            "windSpeed": 2,
                            "windGust": 2.91,
                            "windBearing": 243,
                            "cloudCover": 0.89,
                            "uvIndex": 0,
                            "visibility": 13.615,
                            "ozone": 307.6
                        },
                        {
                            "time": 1580202000,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0334,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.39,
                            "apparentTemperature": 10.39,
                            "dewPoint": 8.75,
                            "humidity": 0.9,
                            "pressure": 1029,
                            "windSpeed": 1.97,
                            "windGust": 2.81,
                            "windBearing": 244,
                            "cloudCover": 0.88,
                            "uvIndex": 0,
                            "visibility": 13.212,
                            "ozone": 307.3
                        },
                        {
                            "time": 1580205600,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0341,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.42,
                            "apparentTemperature": 10.42,
                            "dewPoint": 8.89,
                            "humidity": 0.9,
                            "pressure": 1028.8,
                            "windSpeed": 1.94,
                            "windGust": 2.95,
                            "windBearing": 238,
                            "cloudCover": 0.88,
                            "uvIndex": 0,
                            "visibility": 13.396,
                            "ozone": 308.2
                        },
                        {
                            "time": 1580209200,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0379,
                            "precipProbability": 0.04,
                            "precipType": "rain",
                            "temperature": 10.49,
                            "apparentTemperature": 10.49,
                            "dewPoint": 9.03,
                            "humidity": 0.91,
                            "pressure": 1028.5,
                            "windSpeed": 1.9,
                            "windGust": 3.16,
                            "windBearing": 223,
                            "cloudCover": 0.9,
                            "uvIndex": 0,
                            "visibility": 13.659,
                            "ozone": 309.9
                        },
                        {
                            "time": 1580212800,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0374,
                            "precipProbability": 0.04,
                            "precipType": "rain",
                            "temperature": 10.56,
                            "apparentTemperature": 10.56,
                            "dewPoint": 9.11,
                            "humidity": 0.91,
                            "pressure": 1028.3,
                            "windSpeed": 1.89,
                            "windGust": 3.23,
                            "windBearing": 210,
                            "cloudCover": 0.92,
                            "uvIndex": 0,
                            "visibility": 13.868,
                            "ozone": 311.9
                        },
                        {
                            "time": 1580216400,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0213,
                            "precipProbability": 0.04,
                            "precipType": "rain",
                            "temperature": 10.58,
                            "apparentTemperature": 10.58,
                            "dewPoint": 9.16,
                            "humidity": 0.91,
                            "pressure": 1028.2,
                            "windSpeed": 1.91,
                            "windGust": 2.96,
                            "windBearing": 204,
                            "cloudCover": 0.95,
                            "uvIndex": 0,
                            "visibility": 13.904,
                            "ozone": 314
                        },
                        {
                            "time": 1580220000,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0078,
                            "precipProbability": 0.05,
                            "precipType": "rain",
                            "temperature": 10.61,
                            "apparentTemperature": 10.61,
                            "dewPoint": 9.22,
                            "humidity": 0.91,
                            "pressure": 1028.1,
                            "windSpeed": 1.96,
                            "windGust": 2.56,
                            "windBearing": 199,
                            "cloudCover": 0.97,
                            "uvIndex": 0,
                            "visibility": 13.908,
                            "ozone": 316.5
                        },
                        {
                            "time": 1580223600,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0057,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 10.71,
                            "apparentTemperature": 10.71,
                            "dewPoint": 9.31,
                            "humidity": 0.91,
                            "pressure": 1028.2,
                            "windSpeed": 2.07,
                            "windGust": 2.4,
                            "windBearing": 195,
                            "cloudCover": 0.99,
                            "uvIndex": 0,
                            "visibility": 14.199,
                            "ozone": 318.9
                        },
                        {
                            "time": 1580227200,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 10.84,
                            "apparentTemperature": 10.84,
                            "dewPoint": 9.51,
                            "humidity": 0.92,
                            "pressure": 1028.2,
                            "windSpeed": 2.28,
                            "windGust": 2.78,
                            "windBearing": 190,
                            "cloudCover": 0.99,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 321.2
                        },
                        {
                            "time": 1580230800,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 10.94,
                            "apparentTemperature": 10.94,
                            "dewPoint": 9.66,
                            "humidity": 0.92,
                            "pressure": 1028.3,
                            "windSpeed": 2.55,
                            "windGust": 3.4,
                            "windBearing": 185,
                            "cloudCover": 0.98,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 323.4
                        },
                        {
                            "time": 1580234400,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0,
                            "precipProbability": 0,
                            "temperature": 11.13,
                            "apparentTemperature": 11.13,
                            "dewPoint": 9.79,
                            "humidity": 0.91,
                            "pressure": 1028.6,
                            "windSpeed": 2.74,
                            "windGust": 3.83,
                            "windBearing": 185,
                            "cloudCover": 0.98,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 325.6
                        },
                        {
                            "time": 1580238000,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0355,
                            "precipProbability": 0.09,
                            "precipType": "rain",
                            "temperature": 11.51,
                            "apparentTemperature": 11.51,
                            "dewPoint": 9.89,
                            "humidity": 0.9,
                            "pressure": 1028.5,
                            "windSpeed": 2.81,
                            "windGust": 3.8,
                            "windBearing": 194,
                            "cloudCover": 0.98,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 328.4
                        },
                        {
                            "time": 1580241600,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.1613,
                            "precipProbability": 0.17,
                            "precipType": "rain",
                            "temperature": 11.99,
                            "apparentTemperature": 11.99,
                            "dewPoint": 10.04,
                            "humidity": 0.88,
                            "pressure": 1028.3,
                            "windSpeed": 2.81,
                            "windGust": 3.6,
                            "windBearing": 207,
                            "cloudCover": 0.99,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 331.3
                        },
                        {
                            "time": 1580245200,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.2701,
                            "precipProbability": 0.21,
                            "precipType": "rain",
                            "temperature": 12.57,
                            "apparentTemperature": 12.57,
                            "dewPoint": 10.27,
                            "humidity": 0.86,
                            "pressure": 1028,
                            "windSpeed": 2.8,
                            "windGust": 3.55,
                            "windBearing": 213,
                            "cloudCover": 0.99,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 333.5
                        },
                        {
                            "time": 1580248800,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.2012,
                            "precipProbability": 0.12,
                            "precipType": "rain",
                            "temperature": 12.99,
                            "apparentTemperature": 12.99,
                            "dewPoint": 10.49,
                            "humidity": 0.85,
                            "pressure": 1027.3,
                            "windSpeed": 2.81,
                            "windGust": 3.73,
                            "windBearing": 216,
                            "cloudCover": 0.97,
                            "uvIndex": 2,
                            "visibility": 16.093,
                            "ozone": 334.8
                        },
                        {
                            "time": 1580252400,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0929,
                            "precipProbability": 0.05,
                            "precipType": "rain",
                            "temperature": 13.2,
                            "apparentTemperature": 13.2,
                            "dewPoint": 10.7,
                            "humidity": 0.85,
                            "pressure": 1026.5,
                            "windSpeed": 2.8,
                            "windGust": 4.01,
                            "windBearing": 261,
                            "cloudCover": 0.96,
                            "uvIndex": 1,
                            "visibility": 16.093,
                            "ozone": 335.3
                        },
                        {
                            "time": 1580256000,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0516,
                            "precipProbability": 0.03,
                            "precipType": "rain",
                            "temperature": 13.03,
                            "apparentTemperature": 13.03,
                            "dewPoint": 10.81,
                            "humidity": 0.86,
                            "pressure": 1026,
                            "windSpeed": 2.82,
                            "windGust": 4.28,
                            "windBearing": 244,
                            "cloudCover": 0.94,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 335.3
                        },
                        {
                            "time": 1580259600,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0298,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 12.57,
                            "apparentTemperature": 12.57,
                            "dewPoint": 10.5,
                            "humidity": 0.87,
                            "pressure": 1026,
                            "windSpeed": 2.94,
                            "windGust": 4.56,
                            "windBearing": 180,
                            "cloudCover": 0.9,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 334.6
                        },
                        {
                            "time": 1580263200,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0148,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 11.89,
                            "apparentTemperature": 11.89,
                            "dewPoint": 9.93,
                            "humidity": 0.88,
                            "pressure": 1026.3,
                            "windSpeed": 3.09,
                            "windGust": 4.85,
                            "windBearing": 351,
                            "cloudCover": 0.84,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 333.3
                        },
                        {
                            "time": 1580266800,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0117,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 11.29,
                            "apparentTemperature": 11.29,
                            "dewPoint": 9.34,
                            "humidity": 0.88,
                            "pressure": 1026.6,
                            "windSpeed": 3.16,
                            "windGust": 4.99,
                            "windBearing": 289,
                            "cloudCover": 0.82,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 332.2
                        },
                        {
                            "time": 1580270400,
                            "summary": "Ciel Nuageux",
                            "icon": "partly-cloudy-night",
                            "precipIntensity": 0.0083,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.83,
                            "apparentTemperature": 10.83,
                            "dewPoint": 8.81,
                            "humidity": 0.87,
                            "pressure": 1026.8,
                            "windSpeed": 3.08,
                            "windGust": 4.87,
                            "windBearing": 274,
                            "cloudCover": 0.85,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 331.7
                        },
                        {
                            "time": 1580274000,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0067,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.52,
                            "apparentTemperature": 10.52,
                            "dewPoint": 8.39,
                            "humidity": 0.87,
                            "pressure": 1027,
                            "windSpeed": 2.91,
                            "windGust": 4.58,
                            "windBearing": 301,
                            "cloudCover": 0.91,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 331.3
                        },
                        {
                            "time": 1580277600,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0076,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.28,
                            "apparentTemperature": 10.28,
                            "dewPoint": 8.12,
                            "humidity": 0.86,
                            "pressure": 1027.1,
                            "windSpeed": 2.74,
                            "windGust": 4.3,
                            "windBearing": 307,
                            "cloudCover": 0.95,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 331.2
                        },
                        {
                            "time": 1580281200,
                            "summary": "Ciel Couvert",
                            "icon": "cloudy",
                            "precipIntensity": 0.0072,
                            "precipProbability": 0.02,
                            "precipType": "rain",
                            "temperature": 10.16,
                            "apparentTemperature": 10.16,
                            "dewPoint": 7.98,
                            "humidity": 0.86,
                            "pressure": 1027.2,
                            "windSpeed": 2.62,
                            "windGust": 4.09,
                            "windBearing": 307,
                            "cloudCover": 0.92,
                            "uvIndex": 0,
                            "visibility": 16.093,
                            "ozone": 331.5
                        }
                    ]
                },
                "daily": {
                    "summary": "Pluie faible aujourd’hui.",
                    "icon": "rain",
                    "data": [
                        {
                            "time": 1580025600,
                            "summary": "Pluie faible dans la matinée.",
                            "icon": "rain",
                            "sunriseTime": 1580052000,
                            "sunsetTime": 1580088420,
                            "moonPhase": 0.07,
                            "precipIntensity": 0.2713,
                            "precipIntensityMax": 1.9485,
                            "precipIntensityMaxTime": 1580036700,
                            "precipProbability": 0.88,
                            "precipType": "rain",
                            "temperatureHigh": 14.63,
                            "temperatureHighTime": 1580074860,
                            "temperatureLow": 9.41,
                            "temperatureLowTime": 1580136120,
                            "apparentTemperatureHigh": 14.35,
                            "apparentTemperatureHighTime": 1580074860,
                            "apparentTemperatureLow": 8.81,
                            "apparentTemperatureLowTime": 1580135700,
                            "dewPoint": 10.6,
                            "humidity": 0.86,
                            "pressure": 1023.5,
                            "windSpeed": 3.47,
                            "windGust": 6.88,
                            "windGustTime": 1580077200,
                            "windBearing": 261,
                            "cloudCover": 0.45,
                            "uvIndex": 3,
                            "uvIndexTime": 1580070660,
                            "visibility": 15.893,
                            "ozone": 313.5,
                            "temperatureMin": 10.46,
                            "temperatureMinTime": 1580111880,
                            "temperatureMax": 14.63,
                            "temperatureMaxTime": 1580074860,
                            "apparentTemperatureMin": 10.73,
                            "apparentTemperatureMinTime": 1580111880,
                            "apparentTemperatureMax": 14.35,
                            "apparentTemperatureMaxTime": 1580074860
                        },
                        {
                            "time": 1580112000,
                            "summary": "Faibles passages nuageux toute la journée.",
                            "icon": "partly-cloudy-day",
                            "sunriseTime": 1580138340,
                            "sunsetTime": 1580174880,
                            "moonPhase": 0.1,
                            "precipIntensity": 0.0181,
                            "precipIntensityMax": 0.0508,
                            "precipIntensityMaxTime": 1580136120,
                            "precipProbability": 0.23,
                            "precipType": "rain",
                            "temperatureHigh": 13.78,
                            "temperatureHighTime": 1580164980,
                            "temperatureLow": 10.12,
                            "temperatureLowTime": 1580201940,
                            "apparentTemperatureHigh": 13.5,
                            "apparentTemperatureHighTime": 1580164980,
                            "apparentTemperatureLow": 10.39,
                            "apparentTemperatureLowTime": 1580201940,
                            "dewPoint": 9.19,
                            "humidity": 0.87,
                            "pressure": 1028.6,
                            "windSpeed": 2.26,
                            "windGust": 4.43,
                            "windGustTime": 1580154840,
                            "windBearing": 265,
                            "cloudCover": 0.41,
                            "uvIndex": 3,
                            "uvIndexTime": 1580156220,
                            "visibility": 15.942,
                            "ozone": 314.9,
                            "temperatureMin": 9.41,
                            "temperatureMinTime": 1580136120,
                            "temperatureMax": 13.78,
                            "temperatureMaxTime": 1580164980,
                            "apparentTemperatureMin": 8.81,
                            "apparentTemperatureMinTime": 1580135700,
                            "apparentTemperatureMax": 13.5,
                            "apparentTemperatureMaxTime": 1580164980
                        },
                        {
                            "time": 1580198400,
                            "summary": "Ciel couvert toute la journée.",
                            "icon": "cloudy",
                            "sunriseTime": 1580224680,
                            "sunsetTime": 1580261340,
                            "moonPhase": 0.13,
                            "precipIntensity": 0.0462,
                            "precipIntensityMax": 0.2708,
                            "precipIntensityMaxTime": 1580245440,
                            "precipProbability": 0.33,
                            "precipType": "rain",
                            "temperatureHigh": 13.48,
                            "temperatureHighTime": 1580252580,
                            "temperatureLow": 7.75,
                            "temperatureLowTime": 1580309700,
                            "apparentTemperatureHigh": 13.2,
                            "apparentTemperatureHighTime": 1580252580,
                            "apparentTemperatureLow": 7.15,
                            "apparentTemperatureLowTime": 1580307960,
                            "dewPoint": 9.42,
                            "humidity": 0.89,
                            "pressure": 1027.7,
                            "windSpeed": 2.54,
                            "windGust": 4.99,
                            "windGustTime": 1580266860,
                            "windBearing": 235,
                            "cloudCover": 0.93,
                            "uvIndex": 2,
                            "uvIndexTime": 1580242740,
                            "visibility": 15.357,
                            "ozone": 325,
                            "temperatureMin": 9.88,
                            "temperatureMinTime": 1580281800,
                            "temperatureMax": 13.48,
                            "temperatureMaxTime": 1580252580,
                            "apparentTemperatureMin": 10.15,
                            "apparentTemperatureMinTime": 1580281800,
                            "apparentTemperatureMax": 13.2,
                            "apparentTemperatureMaxTime": 1580252580
                        },
                        {
                            "time": 1580284800,
                            "summary": "Faibles passages nuageux toute la journée.",
                            "icon": "partly-cloudy-day",
                            "sunriseTime": 1580311080,
                            "sunsetTime": 1580347800,
                            "moonPhase": 0.16,
                            "precipIntensity": 0.0042,
                            "precipIntensityMax": 0.0094,
                            "precipIntensityMaxTime": 1580352840,
                            "precipProbability": 0.12,
                            "precipType": "rain",
                            "temperatureHigh": 14.14,
                            "temperatureHighTime": 1580340720,
                            "temperatureLow": 10.29,
                            "temperatureLowTime": 1580385060,
                            "apparentTemperatureHigh": 13.86,
                            "apparentTemperatureHighTime": 1580340720,
                            "apparentTemperatureLow": 10.56,
                            "apparentTemperatureLowTime": 1580385060,
                            "dewPoint": 7.55,
                            "humidity": 0.82,
                            "pressure": 1025.4,
                            "windSpeed": 2.35,
                            "windGust": 5.05,
                            "windGustTime": 1580354160,
                            "windBearing": 306,
                            "cloudCover": 0.56,
                            "uvIndex": 3,
                            "uvIndexTime": 1580328840,
                            "visibility": 16.093,
                            "ozone": 318,
                            "temperatureMin": 7.75,
                            "temperatureMinTime": 1580309700,
                            "temperatureMax": 14.14,
                            "temperatureMaxTime": 1580340720,
                            "apparentTemperatureMin": 7.15,
                            "apparentTemperatureMinTime": 1580307960,
                            "apparentTemperatureMax": 13.86,
                            "apparentTemperatureMaxTime": 1580340720
                        },
                        {
                            "time": 1580371200,
                            "summary": "Ciel dégagé toute la journée.",
                            "icon": "clear-day",
                            "sunriseTime": 1580397420,
                            "sunsetTime": 1580434320,
                            "moonPhase": 0.19,
                            "precipIntensity": 0.0043,
                            "precipIntensityMax": 0.0204,
                            "precipIntensityMaxTime": 1580385060,
                            "precipProbability": 0.09,
                            "precipType": "rain",
                            "temperatureHigh": 16.2,
                            "temperatureHighTime": 1580427240,
                            "temperatureLow": 10.96,
                            "temperatureLowTime": 1580480940,
                            "apparentTemperatureHigh": 15.92,
                            "apparentTemperatureHighTime": 1580427240,
                            "apparentTemperatureLow": 11.23,
                            "apparentTemperatureLowTime": 1580480940,
                            "dewPoint": 9.97,
                            "humidity": 0.83,
                            "pressure": 1025.1,
                            "windSpeed": 2.06,
                            "windGust": 4.44,
                            "windGustTime": 1580371200,
                            "windBearing": 298,
                            "cloudCover": 0.52,
                            "uvIndex": 3,
                            "uvIndexTime": 1580415540,
                            "visibility": 16.093,
                            "ozone": 305.3,
                            "temperatureMin": 10.29,
                            "temperatureMinTime": 1580385060,
                            "temperatureMax": 16.2,
                            "temperatureMaxTime": 1580427240,
                            "apparentTemperatureMin": 10.56,
                            "apparentTemperatureMinTime": 1580385060,
                            "apparentTemperatureMax": 15.92,
                            "apparentTemperatureMaxTime": 1580427240
                        },
                        {
                            "time": 1580457600,
                            "summary": "Faibles passages nuageux toute la journée.",
                            "icon": "partly-cloudy-day",
                            "sunriseTime": 1580483760,
                            "sunsetTime": 1580520780,
                            "moonPhase": 0.22,
                            "precipIntensity": 0.0031,
                            "precipIntensityMax": 0.0073,
                            "precipIntensityMaxTime": 1580487600,
                            "precipProbability": 0.11,
                            "precipType": "rain",
                            "temperatureHigh": 17.38,
                            "temperatureHighTime": 1580512260,
                            "temperatureLow": 10.17,
                            "temperatureLowTime": 1580567940,
                            "apparentTemperatureHigh": 17.1,
                            "apparentTemperatureHighTime": 1580512260,
                            "apparentTemperatureLow": 10.44,
                            "apparentTemperatureLowTime": 1580567940,
                            "dewPoint": 10.32,
                            "humidity": 0.82,
                            "pressure": 1026.5,
                            "windSpeed": 1.51,
                            "windGust": 3.76,
                            "windGustTime": 1580510940,
                            "windBearing": 11,
                            "cloudCover": 0.42,
                            "uvIndex": 3,
                            "uvIndexTime": 1580502720,
                            "visibility": 16.093,
                            "ozone": 306.9,
                            "temperatureMin": 10.96,
                            "temperatureMinTime": 1580480940,
                            "temperatureMax": 17.38,
                            "temperatureMaxTime": 1580512260,
                            "apparentTemperatureMin": 11.23,
                            "apparentTemperatureMinTime": 1580480940,
                            "apparentTemperatureMax": 17.1,
                            "apparentTemperatureMaxTime": 1580512260
                        },
                        {
                            "time": 1580544000,
                            "summary": "Faibles passages nuageux toute la journée.",
                            "icon": "partly-cloudy-day",
                            "sunriseTime": 1580570100,
                            "sunsetTime": 1580607240,
                            "moonPhase": 0.25,
                            "precipIntensity": 0.0025,
                            "precipIntensityMax": 0.0074,
                            "precipIntensityMaxTime": 1580563200,
                            "precipProbability": 0.08,
                            "precipType": "rain",
                            "temperatureHigh": 18.56,
                            "temperatureHighTime": 1580599200,
                            "temperatureLow": 9.56,
                            "temperatureLowTime": 1580654340,
                            "apparentTemperatureHigh": 18.28,
                            "apparentTemperatureHighTime": 1580599200,
                            "apparentTemperatureLow": 7.67,
                            "apparentTemperatureLowTime": 1580654460,
                            "dewPoint": 10.32,
                            "humidity": 0.82,
                            "pressure": 1025.4,
                            "windSpeed": 2.29,
                            "windGust": 3.28,
                            "windGustTime": 1580587140,
                            "windBearing": 15,
                            "cloudCover": 0.49,
                            "uvIndex": 3,
                            "uvIndexTime": 1580588940,
                            "visibility": 16.093,
                            "ozone": 303.7,
                            "temperatureMin": 10.17,
                            "temperatureMinTime": 1580567940,
                            "temperatureMax": 18.56,
                            "temperatureMaxTime": 1580599200,
                            "apparentTemperatureMin": 10.44,
                            "apparentTemperatureMinTime": 1580567940,
                            "apparentTemperatureMax": 18.28,
                            "apparentTemperatureMaxTime": 1580599200
                        },
                        {
                            "time": 1580630400,
                            "summary": "Faibles passages nuageux toute la journée.",
                            "icon": "partly-cloudy-day",
                            "sunriseTime": 1580656440,
                            "sunsetTime": 1580693700,
                            "moonPhase": 0.29,
                            "precipIntensity": 0.0062,
                            "precipIntensityMax": 0.0211,
                            "precipIntensityMaxTime": 1580652240,
                            "precipProbability": 0.1,
                            "precipType": "rain",
                            "temperatureHigh": 14.56,
                            "temperatureHighTime": 1580677860,
                            "temperatureLow": 6.72,
                            "temperatureLowTime": 1580741040,
                            "apparentTemperatureHigh": 14.28,
                            "apparentTemperatureHighTime": 1580677860,
                            "apparentTemperatureLow": 4.33,
                            "apparentTemperatureLowTime": 1580741340,
                            "dewPoint": 6.82,
                            "humidity": 0.75,
                            "pressure": 1020.4,
                            "windSpeed": 5.22,
                            "windGust": 13.57,
                            "windGustTime": 1580699160,
                            "windBearing": 303,
                            "cloudCover": 0.24,
                            "uvIndex": 3,
                            "uvIndexTime": 1580674500,
                            "visibility": 16.093,
                            "ozone": 312,
                            "temperatureMin": 9.09,
                            "temperatureMinTime": 1580716800,
                            "temperatureMax": 14.56,
                            "temperatureMaxTime": 1580677860,
                            "apparentTemperatureMin": 6.37,
                            "apparentTemperatureMinTime": 1580716800,
                            "apparentTemperatureMax": 14.28,
                            "apparentTemperatureMaxTime": 1580677860
                        }
                    ]
                },
                "flags": {
                    "sources": [
                        "nwspa",
                        "cmc",
                        "gfs",
                        "hrrr",
                        "icon",
                        "isd",
                        "madis",
                        "nam",
                        "sref",
                        "darksky",
                        "nearest-precip"
                    ],
                    "nearest-station": 3.604,
                    "units": "si"
                },
                "offset": -8
            }
            """
        }
        guard let data = encodable.data(using: .utf8) else {
            fatalError("Please set a valide exemple")
        }
        return data
    }
}
