language: swift
osx_image: xcode11.3

jobs:
  include:
    - script: xcodebuild clean build test -workspace Baluchon.xcworkspace -scheme Baluchon -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO